boulder:
    build: .
    dockerfile: Dockerfile
    ports:
        - "4000:4000"
    environment:
        MYSQL_CONTAINER: "yes"
    links:
      - mysql
      - rabbitmq
mysql:
    image: mariadb:10
    expose:
        - "3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
rabbitmq:
    image: rabbitmq:3
    expose:
        - "5672"
