# see comments in test/run-docker.sh about host networking
boulder:
    build: .
    dockerfile: Dockerfile
    ports:
        - "4000:4000"
          #- "4001:4001"
        - "4002:4002"
    environment:
        MYSQL_CONTAINER: "yes"
    links:
      - mysql
      - rabbitmq
mysql:
    image: mariadb:10.0
    expose:
        - "3306"
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
        -  /srv/docker_voumes/mariadb10:/var/lib/mysql
rabbitmq:
    image: rabbitmq:3
    expose:
        - "5672"
